environment:
  matrix:
   - nodejs: "5"
install:
 - ps: Install-Product node $env:nodejs
 - npm install
 - set PATH=%CD%\node_modules\.bin;%PATH%
matrix:
 fast_finish: true
build: off
version: "{build}"
shallow_clone: true
clone_depth: 1
test_script:
 - node --version
 - npm --version
 - mocha
